sudo: required
services:
  - docker

before_install:
  - docker build -t travis/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true travis/docker-react npm run test -- -- coverage

language: generic
