version: "3.9"
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
    stdin_open: true
    tty: true